-- Auto generated by WoWBench 3.0.3.a2 from "D:/OneDrives/OneDrive/Development work/Warcraft Addons/PriorityLoot/embeds.xml" on 2025-01-09 06:33:40
local WOWB_XMLFILE="D:/OneDrives/OneDrive/Development work/Warcraft Addons/PriorityLoot/embeds.xml";
local WOWB_XMLFILENOPATH="D:/OneDrives/OneDrive/Development work/Warcraft Addons/PriorityLoot/embeds.xml";
local WOWB_TAG = { [0]={content=""} }
local WOWB_PARENTOBJECT = WOWB_RootFrame;
local xfpc = WOWB_XMLFileParserContext:New(WOWB_XMLFILE);

do -- <Ui ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=1
local WOWB_TAG = { [0]={  xmltag="Ui",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=1,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["xmlns:xsd"] ="http://www.w3.org/2001/XMLSchema",
["xmlns:xsi"] ="http://www.w3.org/2001/XMLSchema-instance",
["xmlns"] ="http://www.blizzard.com/wow/ui/",
}};
WOWB_PARENT[0]["Ui"] = WOWB_TAG;
do -- <Script ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=2
local WOWB_TAG = { [0]={  xmltag="Script",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=2,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["file"] ="Libs\\LibStub\\LibStub.lua",
}};
if not WOWB_EXECCOMPILED then
  WOWB_ParseXML_dofile(xfpc, WOWB_TAG[0].file);
end
tinsert(WOWB_PARENT[0], WOWB_TAG);
WOWB_ParseXML_CompileScriptNode(xfpc:Recurse(WOWB_TAG), WOWB_TAG);end -- Script
do -- <Include ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=4
local WOWB_TAG = { [0]={  xmltag="Include",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=4,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["file"] ="Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.xml",
}};
if not WOWB_EXECCOMPILED then
  local prevCWD = _CWD;
  local filename;
  filename,_CWD = WOWB_ProcessFilename(WOWB_TAG[0].file, true);
  WOWB_ParseXML(filename);
  _CWD = prevCWD;
  tinsert(WOWB_AllFilesForTOC, filename);
end
end -- Include
do -- <Include ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=5
local WOWB_TAG = { [0]={  xmltag="Include",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=5,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["file"] ="Libs\\AceAddon-3.0\\AceAddon-3.0.xml",
}};
if not WOWB_EXECCOMPILED then
  local prevCWD = _CWD;
  local filename;
  filename,_CWD = WOWB_ProcessFilename(WOWB_TAG[0].file, true);
  WOWB_ParseXML(filename);
  _CWD = prevCWD;
  tinsert(WOWB_AllFilesForTOC, filename);
end
end -- Include
do -- <Include ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=6
local WOWB_TAG = { [0]={  xmltag="Include",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=6,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["file"] ="Libs\\AceConsole-3.0\\AceConsole-3.0.xml",
}};
if not WOWB_EXECCOMPILED then
  local prevCWD = _CWD;
  local filename;
  filename,_CWD = WOWB_ProcessFilename(WOWB_TAG[0].file, true);
  WOWB_ParseXML(filename);
  _CWD = prevCWD;
  tinsert(WOWB_AllFilesForTOC, filename);
end
end -- Include
do -- <Include ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=7
local WOWB_TAG = { [0]={  xmltag="Include",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=7,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["file"] ="Libs\\AceEvent-3.0\\AceEvent-3.0.xml",
}};
if not WOWB_EXECCOMPILED then
  local prevCWD = _CWD;
  local filename;
  filename,_CWD = WOWB_ProcessFilename(WOWB_TAG[0].file, true);
  WOWB_ParseXML(filename);
  _CWD = prevCWD;
  tinsert(WOWB_AllFilesForTOC, filename);
end
end -- Include
end -- Ui
if not WOWB_TAG[0][WOWB_ROOTXMLTAG] then xfpc:error("No <"..WOWB_ROOTXMLTAG.."> tag?"); end
WOWB_ParseXML_QueueScripts(WOWB_TAG[0][WOWB_ROOTXMLTAG]);

xfpc:Return();
